apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2023-05-11T19:47:51Z"
  generation: 1
  name: monitoring-flask-app
  namespace: default
  resourceVersion: "154914"
  uid: 3a45addc-b39c-4962-99fe-1bec7dcc06ac
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: monitoring-flask-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: monitoring-flask-app
    spec:
      containers:
      - image: 910099015354.dkr.ecr.us-east-1.amazonaws.com/flask_monitoring_app_repo:latest
        imagePullPolicy: Always
        name: monitoring-flask-container
        ports:
        - containerPort: 5010
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2023-05-11T19:47:51Z"
    lastUpdateTime: "2023-05-11T19:47:51Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2023-05-11T19:47:51Z"
    lastUpdateTime: "2023-05-11T19:47:52Z"
    message: ReplicaSet "monitoring-flask-app-74c846c996" is progressing.
    reason: ReplicaSetUpdated
    status: "True"
    type: Progressing
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
