apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-05-11T19:47:51Z"
  name: monitoring-flask-service
  namespace: default
  resourceVersion: "154902"
  uid: 33d73c81-ec5a-48e6-bae7-4e3c3cb334cb
spec:
  clusterIP: 10.100.10.131
  clusterIPs:
  - 10.100.10.131
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 5010
    protocol: TCP
    targetPort: 5010
  selector:
    app: monitoring-flask-app
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
